# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trigger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from TriggerClass import Trigger, TriggerHandler
from HelperWindows import DataFrameView, StandardErrorDialog
import os
import sys


class Ui_TriggerWindow(object):
    def setupUi(self, TriggerWindow):
        TriggerWindow.setObjectName("TriggerWindow")
        TriggerWindow.resize(355, 257)
        self.centralwidget = QtWidgets.QWidget(TriggerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RelationLayout = QtWidgets.QHBoxLayout()
        self.RelationLayout.setObjectName("RelationLayout")
        self.RelationLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RelationLabel.setFont(font)
        self.RelationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RelationLabel.setObjectName("RelationLabel")
        self.RelationLayout.addWidget(self.RelationLabel)
        self.RelationComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RelationComboBox.setFont(font)
        self.RelationComboBox.setObjectName("RelationComboBox")
        self.RelationComboBox.addItem("")
        self.RelationComboBox.addItem("")
        self.RelationComboBox.addItem("")
        self.RelationComboBox.addItem("")
        self.RelationComboBox.addItem("")
        self.RelationLayout.addWidget(self.RelationComboBox)
        self.gridLayout.addLayout(self.RelationLayout, 1, 0, 1, 1)
        self.NameLayout = QtWidgets.QHBoxLayout()
        self.NameLayout.setObjectName("NameLayout")
        self.NameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NameLabel.setFont(font)
        self.NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel.setObjectName("NameLabel")
        self.NameLayout.addWidget(self.NameLabel)
        self.NameText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameText.sizePolicy().hasHeightForWidth())
        self.NameText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameText.setFont(font)
        self.NameText.setObjectName("NameText")
        self.NameLayout.addWidget(self.NameText)
        self.gridLayout.addLayout(self.NameLayout, 3, 0, 1, 1)
        self.DeactivateLayout = QtWidgets.QHBoxLayout()
        self.DeactivateLayout.setObjectName("DeactivateLayout")
        self.DeactivateLable = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DeactivateLable.setFont(font)
        self.DeactivateLable.setAlignment(QtCore.Qt.AlignCenter)
        self.DeactivateLable.setObjectName("DeactivateLable")
        self.DeactivateLayout.addWidget(self.DeactivateLable)
        self.DeactivateComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DeactivateComboBox.setFont(font)
        self.DeactivateComboBox.setMaxVisibleItems(10)
        self.DeactivateComboBox.setObjectName("DeactivateComboBox")
        self.DeactivateComboBox.addItem("")
        self.DeactivateComboBox.addItem("")
        self.DeactivateLayout.addWidget(self.DeactivateComboBox)
        self.gridLayout.addLayout(self.DeactivateLayout, 4, 0, 1, 1)
        self.ValueLayout = QtWidgets.QHBoxLayout()
        self.ValueLayout.setObjectName("ValueLayout")
        self.ValueLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ValueLabel.setFont(font)
        self.ValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ValueLabel.setObjectName("ValueLabel")
        self.ValueLayout.addWidget(self.ValueLabel)
        self.ValueText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValueText.sizePolicy().hasHeightForWidth())
        self.ValueText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ValueText.setFont(font)
        self.ValueText.setObjectName("ValueText")
        self.ValueLayout.addWidget(self.ValueText)
        self.gridLayout.addLayout(self.ValueLayout, 2, 0, 1, 1)
        self.SymbolLayout = QtWidgets.QHBoxLayout()
        self.SymbolLayout.setObjectName("SymbolLayout")
        self.SymbolLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SymbolLabel.setFont(font)
        self.SymbolLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SymbolLabel.setObjectName("SymbolLabel")
        self.SymbolLayout.addWidget(self.SymbolLabel)
        self.SymbolText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SymbolText.sizePolicy().hasHeightForWidth())
        self.SymbolText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SymbolText.setFont(font)
        self.SymbolText.setText("")
        self.SymbolText.setObjectName("SymbolText")
        self.SymbolLayout.addWidget(self.SymbolText)
        self.gridLayout.addLayout(self.SymbolLayout, 0, 0, 1, 1)
        self.ButtonLayout = QtWidgets.QHBoxLayout()
        self.ButtonLayout.setObjectName("ButtonLayout")
        self.AddButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddButton.setFont(font)
        self.AddButton.setObjectName("AddButton")
        self.ButtonLayout.addWidget(self.AddButton)
        self.DeleteButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.ButtonLayout.addWidget(self.DeleteButton)
        self.ListButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListButton.sizePolicy().hasHeightForWidth())
        self.ListButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListButton.setFont(font)
        self.ListButton.setObjectName("ListButton")
        self.ButtonLayout.addWidget(self.ListButton)
        self.gridLayout.addLayout(self.ButtonLayout, 5, 0, 1, 1)
        TriggerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TriggerWindow)
        self.statusbar.setObjectName("statusbar")
        TriggerWindow.setStatusBar(self.statusbar)

        self.AddButton.clicked.connect(self.addTrigger)
        self.DeleteButton.clicked.connect(self.deleteTrigger)
        self.ListButton.clicked.connect(self.listTriggers)

        self.TrigHand = TriggerHandler.fromJson()

        self.retranslateUi(TriggerWindow)
        QtCore.QMetaObject.connectSlotsByName(TriggerWindow)

    def retranslateUi(self, TriggerWindow):
        _translate = QtCore.QCoreApplication.translate
        TriggerWindow.setWindowTitle(_translate("TriggerWindow", "Trigger GUI"))
        self.RelationLabel.setText(_translate("TriggerWindow", "Relation"))
        self.RelationComboBox.setItemText(0, _translate("TriggerWindow", "<="))
        self.RelationComboBox.setItemText(1, _translate("TriggerWindow", "<"))
        self.RelationComboBox.setItemText(2, _translate("TriggerWindow", ">="))
        self.RelationComboBox.setItemText(3, _translate("TriggerWindow", ">"))
        self.RelationComboBox.setItemText(4, _translate("TriggerWindow", "="))
        self.NameLabel.setText(_translate("TriggerWindow", "Trigger Name"))
        self.DeactivateLable.setText(_translate("TriggerWindow", "Deactivate on Trigger?"))
        self.DeactivateComboBox.setItemText(0, _translate("TriggerWindow", "Yes"))
        self.DeactivateComboBox.setItemText(1, _translate("TriggerWindow", "No"))
        self.ValueLabel.setText(_translate("TriggerWindow", "Value"))
        self.SymbolLabel.setText(_translate("TriggerWindow", "Symbol"))
        self.AddButton.setText(_translate("TriggerWindow", "Add Trigger"))
        self.DeleteButton.setText(_translate("TriggerWindow", "Delete Trigger"))
        self.ListButton.setText(_translate("TriggerWindow", "List all Triggers"))

    def addTrigger(self):
        relationOpStr = {
            "<=": "LE",
            "<": "LT",
            ">=": "GE",
            ">": "GT",
            "=": "EQ"
        }
        deactivateStrBool = {
            "Yes": True,
            "No": False
        }
        try:
            name = self.NameText.text()
            value = float(self.ValueText.text())
            symbol = self.SymbolText.text()
            relation = relationOpStr[self.RelationComboBox.currentText()]
            deactivate = deactivateStrBool[self.DeactivateComboBox.currentText()]
        except:  # noqa: E722
            self.dialog = StandardErrorDialog(parent=None, text="Something is empty or wrong, name, value or symbol")
            self.dialog.ui.pushButton.clicked.connect(self.dialog.close)
            self.dialog.exec()
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            print("ERROR! Type: {}, File: {}, Line: {}".format(exc_type, fname, exc_tb.tb_lineno))
            return

        if len(name) == 0 or value <= 0 or len(symbol) == 0:
            self.dialog = StandardErrorDialog(parent=None, text=f"Something is empty or wrong, {name} {value} {symbol}")
            self.dialog.ui.pushButton.clicked.connect(self.dialog.close)
            self.dialog.exec()
            return

        trigger = Trigger(symbol, value, relation, name, deactivate)

        retVal = self.TrigHand.addTrigger(trigger)

        if retVal == -1:
            self.dialog = StandardErrorDialog(parent=None, text=f"Name already exists, can't add this trigger with this name: {name}")
            self.dialog.ui.pushButton.clicked.connect(self.dialog.close)
            self.dialog.exec()
            return

        self.TrigHand.toJsonFile()

    def deleteTrigger(self):
        name = self.NameText.text()

        if len(name) == 0:
            self.dialog = StandardErrorDialog(parent=None, text="Name is empty, please add a valid name!")
            self.dialog.ui.pushButton.clicked.connect(self.dialog.close)
            self.dialog.exec()
            return

        retVal = self.TrigHand.deleteTrigger(name)

        if retVal == 1:
            self.dialog = StandardErrorDialog(parent=None, text=f"No trigger exists with this name: {name}")
            self.dialog.ui.pushButton.clicked.connect(self.dialog.close)
            self.dialog.exec()
            print("No trigger exists with this name")

        self.TrigHand.toJsonFile()

    def listTriggers(self):
        df = self.TrigHand.listAllTriggers()
        self.dataWindow = DataFrameView()
        self.dataWindow.setData(df)
        self.dataWindow.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    TriggerWindow = QtWidgets.QMainWindow()
    ui = Ui_TriggerWindow()
    ui.setupUi(TriggerWindow)
    TriggerWindow.show()
    sys.exit(app.exec_())
